### ISSUE TITLE
LICENSE update 

### ISSUE THREAD

**Issue by 3imed-jaberi** [jelhouss/thio#9]
You should change the 1st line of the LICENSE file to `Copyright 2019-2020 Houssam Jelliti <jelitihoussam@gmail.com>` .. 

---
Sorry I don't have time to make a fork and do this ..

**Comment by jelhouss** [comment]
Hi Imed, thank you for opening this ton of issues, I really appreciate the care mate :heart_eyes: Please take your time reading this long response.
Just a small word (as I whisper) please don't write (Sorry I don't have time to make a fork and do this) in the end of any issue, I don't think people who maintain projects would love it. :blush:

As I organise issues when I work, I am going to close all issues (**this one included**) and I would love to have one single issue with explanations and organised points, below are the one **I welcome you to write them in a new issue and organise them point by point please, with "enhancements" label included, and a title like "Enhancements 1" (simply like that).**
Issues: #9 (this one), #10,  #17 

**I also want you to open another issue with title "Enhancements 2" and also with label "question" included**, for the below issues, I want to open a discussion there and leave those as future enhancements.
#11, #13, #16 with more explanation please for #13 and #16 (I think tests work fine, they are small and fit IMO).

Below issues are closed as they are not important, I will explain why.
#15: 
- `.map()` here is not efficient as the terminology of `.map()` applies with a piece code that will be applied for all the elements all together. `.forEach()` here has a bit of heavy logic, and I don't want to apply this logic with the terminology of `.map()` it wouldn't take advantage of mapping, this is how I understand `.map()` work if you think otherwise please elaborate more.
- I don't really remember how many times I used `.toString()` ? but I don't know if that would make a problem anyway.
- For the jsDoc form you're right, that would be better, I will take care of that in the future, but for now that syntax is just small and doesn't follow the jsDoc conventions already, imagine them as just simple comments that looks like jsDoc comments.
- ES7+ features, I don't know man, didn't yet encounter something that needs ES7+, and I don't want to use a lot of deps. One of the things I am doing recently is not depend on tooling too much.

#12: This is a biased-opinion (sorry LOL), but I like the current import/export strategy.

#14: You're right, that due to not having a linter, and also commiting a change from my computer at work which has a linter that lint against double-quotes, and in the [this commit](https://github.com/jelhouss/thio/commit/75b9946c488cdfe2f3a0802828d774ff72a2079e) I already mentioned that in the commit message.


Thank you for baring with me. Please if you open the two issues `Enhancements 1` and `Enhancements 2` that would mean a lot.

P.s. I don't have time to work on the project in these upcoming months, but will be back and I think I am going to make a lot of changes.
